//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ENROLLMENTS
    {
        public int Enrollment_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
    
        public virtual TB_CLASSES TB_CLASSES { get; set; }
        public virtual TB_STUDENTS TB_STUDENTS { get; set; }
    }
}
